### ISSUE TITLE
map style

### ISSUE THREAD

**Issue by GretaCB** [codeforboston/finda#20]
A couple weeks ago, there was discussion about possible map styling. I ran into this today for Google Maps:

http://snazzymaps.com/

**Comment by mjrouser** [comment]
Does this only work with Google maps?  Tiles from OSM are in the code now.

**Comment by ohnorobo** [comment]
I've been looking into switching to mapbox as a tile provider, since they offer close integration with leaflet, and have [lovely](https://www.mapbox.com/tour/) default tiles.

I'm hitting what look like require problems though. @paulswartz if you get a chance could you take a look?
https://github.com/ohnorobo/finda/compare/mapbox

**Comment by paulswartz** [comment]
@ohnorobo it looks like instead of being an attribute, you've made the leaflet instance into the component. All you should need to do is change how 'this.map' is initialized; it's towards the bottom of the file. If you open a pull request I can give you more specific feedback.

What's the usage like on Mapbox? The last time I looked it cost money to use? But they do look nice!

**Comment by ohnorobo** [comment]
https://github.com/codeforboston/finda/pull/47

That was my impression as well, but willtheytow.me seems to be using them without any sort of api key. @carpeliam do you know?

https://www.mapbox.com/plans/?period=year
vs
https://developers.google.com/maps/faq#usagelimits

**Comment by carpeliam** [comment]
I haven't done any actual development on willtheytow.me, though when I first saw the email I think I remember seeing some API keys. You might want to check with @beechnut or @thecristen.

**Comment by thecristen** [comment]
No API key or anything for willtheytow.me. Totally free. Don't know what we're gonna do if our map views hit 3k/month I suppose. Hm.

**Comment by paulswartz** [comment]
@thecristen is it possible that it's using the CoUrbanize keys?

**Comment by paulswartz** [comment]
@calvinmetcalf pointed me to http://leaflet-extras.github.io/leaflet-providers/preview/index.html which has a bunch of providers which don't require use to get an API key or depend on something we might have to pay for.

I'm partial to OpenStreetMap.HOT, MapQuestOpen.OSM, Stamen.Terrain, and Acetate.all.

update: on reflection, I think Acetate is the best of those, in that it looks nice but stays out of the way of the data we're trying to present.

update 2: threw it up on my branch: http://paulswartz.github.io/finda/
