### ISSUE TITLE
Cross Browser Compatibility

### ISSUE THREAD

**Issue by ohnorobo** [codeforboston/finda#24]
I've heard reports of troubles using the site in IE. Legacy browser support is probably too much to ask, but compatibility across all modern browsers should be a goal.

in this issue: include any browser specific problem you're seeing with browser and version number.

**Comment by paulswartz** [comment]
Leaflet only goes back to IE7, so that's the earliest we'll be able to
easily support. Everything else seems to go back that far as well.

**Comment by ohnorobo** [comment]
report from marc:
The version of IE that the state uses is version 8 forward and the problem is that it simply doesn’t load. The page finishes loading but stays blank.

**Comment by StillwellMedia** [comment]
IE8 throws a javascript error if there are console.log() calls in the js and the user does not have the console open.   Production code must be without console.log.  I just looked at the website in a virtual box and there is a console.log error.

**Comment by paulswartz** [comment]
@stillwellmedia thanks for taking a look! I'll hopefully have some time in the next day or two to look at it.

@codeforboston who should I ping to take a look at pull requests?

**Comment by ohnorobo** [comment]
@paulswartz, ping me or @beechnut

**Comment by ohnorobo** [comment]
@paulswartz, @StillwellMedia, all of the console.log is gone after closing Paul's requirejs PR, so hopefully IE should be alright now.

**Comment by StillwellMedia** [comment]
Yep, it looks like it's working now. One other thing, IE8 does not support the HTML5 placeholder attribute, so that "search for address ..." input is blank and has no instructions.

**Comment by paulswartz** [comment]
The tiles load in IE7, but nothing else.

**Comment by paulswartz** [comment]
So I took a look at it and fixed some easy issues on IE8: you can see the result at https://paulswartz.github.io/filter-template/
- only show the geosearch if it's enabled in config.json (I disabled it on my gh-pages) since it doesn't work in IE8
- fixed some issues with the templating causing the info box to render incorrectly.

Let me know if there's anything else and I'll add it to my branch.  I'll put together a pull request when it seems like the issues are taken care of.
