### ISSUE TITLE
searching for features by name

### ISSUE THREAD

**Issue by paulswartz** [codeforboston/finda#69]
Needs some discussion about how it works.

**Comment by garbados** [comment]
How about this approach? http://stackoverflow.com/a/7533498/991961

This provides efficient, rapid, Lucene-like searching against all location properties.

The reference implementation seems to be missing, but I'd be happy to draft a new one.

**Comment by beechnut** [comment]
How about fuzzy search on all attributes?

My colleague @arminakvn just showed me this: https://github.com/naomap/leaflet-fusesearch, implemented here: http://www.naomap.fr/. Fuzzy search on all attributes in a GeoJSON layer.

**Comment by ohnorobo** [comment]
This is pretty slick. The only downside is it doesn't seem to be well
integrated with location search yet. (Try searching for street names.)

I really like the interface though. This would make a good alternative to
some of the facet search workflows we were looking into.

**Comment by beechnut** [comment]
Good news: that's only because they didn't index the addresses!

``` js
var props = ['nom_comple', 'libcategor', 'commune'];
```

But we can.

``` js
var props = [ ..., 'address' ]
```

**Comment by paulswartz** [comment]
Fuse.js/leaflet-fusesearch seem great!  Now the question is just about how the UI/UX should work.  It'd be nice to be able to re-use it for this, but that's a lot of work for a humble box...

**Comment by ohnorobo** [comment]
It's definitely a very different flow from the current search.

Currently we get a string -> geocode it using another magic service -> 
move the user to that geocoded location

Whereas this searches properties and maybe filters on them on the map.

It would be nice to be able to let people put in either of those things 
and have some 'address-like' heuristic deciding what to do, but that's 
probably a bit much.

Paul Swartz wrote:

**Comment by paulswartz** [comment]
I'm going to play around with re-using the search box, and have the workflow be the following:
- type in the search box, and show any matching results
- selecting a matching result will scroll the map to that result and open its info
- hitting enter when there's a result will also select that result (not sure about this one)
- if there aren't any results and the user hits enter, we'll search for that address (current search behavior)

**Comment by paulswartz** [comment]
You can play around with this feature at http://paulswartz.github.io/finda/

**Comment by beechnut** [comment]
Thanks, Paul -- it's really helpful to be able to play with it.

I think having one search box could work well. Here's what I'm finding as I start to use it:
- Showing matching results immediately is really nice -- if users have an idea of what they're looking for, they can go for it.
  - Presently, it only shows the top 5 results, and there might be a lot of results that match a person's query, especially in a dataset like this with a number of frequently-used attributes.
  - Because someone will not be searching and reading the information for a facility at the same time, it may be advisable to move the search to a sidebar, to allow us to display the full results list. I'm not at all confident about this suggestion.

I'm unable to find "Cambridge, MA" and look at the facilities there, since pressing "enter" takes me to the first result for "Cambridge, MA".

Here are my recommendations for immediate changes.:
- Have the default behavior (pressing "enter") be searching for the given address. Explicitly state this in the results box.
- Explicitly mark the results as 'results' or 'suggestions'.

And here's a mockup of what that might look like:

![finda-mockup](https://cloud.githubusercontent.com/assets/1887182/3246155/da6a09da-f178-11e3-97de-8b44cd666f26.jpg)

**Comment by paulswartz** [comment]
Haven't written tests yet, but new code is up: http://paulswartz.github.io/finda/
